### ISSUE TITLE
项目引用了com.google.guava:guava@22.0等169个开源组件，存在1个严重漏洞，建议升级

### ISSUE THREAD

**Issue by AbbyWoo** [vvorks/builder#18]
大佬，我看你这个项目引用了com.google.guava:guava@22.0等169个开源组件，存在1个严重漏洞，建议你升级下。
```
漏洞标题：Google Guava 代码问题漏洞
漏洞描述：
Google Guava是美国谷歌（Google）公司的一款包括图形库、函数类型、I/O和字符串处理等的Java核心库。
Google Guava 11.0版本至24.1.1版本（不包括24.1.1版本）中存在代码问题漏洞。该漏洞源于网络系统或产品的代码开发过程中存在设计或实现不当的问题。
国家漏洞库信息：https://www.cnvd.org.cn/flaw/show/CNVD-2018-10064
漏洞级别：中危
影响范围：[11.0, 24.1.1-android)
最小修复版本：24.1.1-android
引入路径：
builder:->com.google.googlejavaformat:google-java-format@1.6->com.google.guava:guava@22.0
```
还有其它几个漏洞，信息有点多我就不贴了，你自己看下完整报告：https://www.murphysec.com/j?p=a1d2f1

**Comment by vvorks** [comment]
I think that the message was added incorrectly, so I will delete it.

**Comment by vvorks** [comment]
impoliteness. I was using guava indirectly.

**Comment by vvorks** [comment]
I changed the version of guava with the following commit.
Thank you very much.

https://github.com/vvorks/builder/commit/397de494948633fa0b3b03a8311ff9a31d122caa
